CrudNativo/Models/ErrorViewModel.cs
namespace CrudNativo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudNativo/Models/Libro.cs
using System.ComponentModel.DataAnnotations;

namespace CrudNativo.Models
{
    public class Libro
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="El campo es Obligatorio")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "El campo es Obligatorio")]

        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El campo es Obligatorio")]

        public string Autor { get; set;}
        [Required(ErrorMessage = "El campo es Obligatorio")]


        public DateTime FechaPublicacion { get; set; }
        [Required(ErrorMessage = "El campo es Obligatorio")]
        [DataType(DataType.Date)]


        public string Precio { get; set; }
    }
}

CrudNativo/Models/Usuario.cs
namespace CrudNativo.Models
{
    public class Usuario
    {
    }
}

CrudNativo/Controllers/HomeController.cs
using CrudNativo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudNativo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudNativo/Controllers/LibroController.cs
using CrudNativo.Data;
using CrudNativo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace CrudNativo.Controllers
{
    public class LibroController : Controller
    { 
        //Esto es para acceder a la base de datos
        private readonly AplicationDbContext _context; 

        //creamos el contructor

        public LibroController(AplicationDbContext context)
        {
            _context = context;
        }

        //Metodo Get index

        public IActionResult Index()
        {
            //creamos lista de datos IEnumerable
            IEnumerable<Libro> ListLibros = _context.libro;
            return View(ListLibros);//retornar la lista
        }

        //HTTP get create

        public IActionResult create() {
            return View();
        }

        [HttpPost]


        public IActionResult create(Libro libro) {
            if (ModelState.IsValid)
            {
                _context.libro.Add(libro);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(libro);
        }



        //Editar

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //obtener el libro

            var libro = _context.libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }


        //post editar

        [HttpPost]

        [ValidateAntiForgeryToken]  //seguridad de la base da datos

        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.libro.Update(libro);
                _context.SaveChanges();
                return RedirectToAction("index");
            }

            return View();


        }




        //get eliminar


       
        public IActionResult Delete(int? id)
        {
            var libro = _context.libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }

            _context.libro.Remove(libro);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CrudNativo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrudNativo/Views/Libro/Edit.cshtml
@model CrudNativo.Models.Libro
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>



<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form method="post" asp-action="Edit">
                <!--para validar el lado del servidor-->
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control.label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Descripcion" class="control.label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Autor" class="control.label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaPublicacion" class="control.label"></label>
                    <input asp-for="FechaPublicacion" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control.label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value=" Agregar libro" class="btn btn-primary" />
                </div>



            </form>
        </div>
    </div>
</div>

CrudNativo/Views/Libro/Index.cshtml
@model IEnumerable<CrudNativo.Models.Libro>
@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Libros</h1>

<div class="row">
    <div class=" col-sm-6">
        <a class=" btn btn-success d-block" asp-action="create" asp-controller="Libro">Agregar</a>
    </div>
</div>

<div class="row">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <td>@Html.DisplayNameFor(a => a.Id)</td>
                <td>@Html.DisplayNameFor(a => a.Titulo)</td>
                <td>@Html.DisplayNameFor(a => a.Descripcion)</td>
                <td>@Html.DisplayNameFor(a => a.Autor)</td>
                <td>@Html.DisplayNameFor(a => a.FechaPublicacion)</td>
                <td>@Html.DisplayNameFor(a => a.Precio)</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            <!-- para que se recorra los registros-->
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Titulo</td>
                    <td>@item.Descripcion</td>
                    <td>@item.FechaPublicacion</td>
                    <td>@item.Autor</td>
                    <td>@item.Precio</td>
                    <td>Acciones</td>
                    <td>
                        <a asp-controller="Libro" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                        <a asp-controller="Libro" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>




            }

        </tbody>
    </table>

CrudNativo/Views/Libro/create.cshtml
@model CrudNativo.Models.Libro
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form method="post" asp-action="Create">
                <!--para validar el lado del servidor-->
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titulo" class="control.label"></label>
                    <input asp-for="Titulo" class="form-control"/>
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Descripcion" class="control.label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Autor" class="control.label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaPublicacion" class="control.label"></label>
                    <input asp-for="FechaPublicacion" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Precio" class="control.label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <!-- para validar del lado del cliente-->
                    <span asp-asp-validation-for="Titulo" class="Text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value=" Agregar libro" class="btn btn-primary">
                </div>



            </form>
        </div>
    </div>
</div>

CrudNativo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudNativo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudNativo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudNativo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libro" asp-action="index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CrudNativo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>